// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconCarbonArrowUp: typeof import('~icons/carbon/arrow-up.jsx')['default']
  const IconCarbonChevronLeft: typeof import('~icons/carbon/chevron-left.jsx')['default']
  const IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right.jsx')['default']
  const IconCarbonLanguage: typeof import('~icons/carbon/language.jsx')['default']
  const IconCarbonLight: typeof import('~icons/carbon/light.jsx')['default']
  const IconCarbonMoon: typeof import('~icons/carbon/moon.jsx')['default']
  const IconCibWhatsapp: typeof import('~icons/cib/whatsapp.jsx')['default']
  const IconEntypoInfoWithCircle: typeof import('~icons/entypo/info-with-circle.jsx')['default']
  const IconEvaGithubOutline: typeof import('~icons/eva/github-outline.jsx')['default']
  const IconFaBrandsLinkedinIn: typeof import('~icons/fa-brands/linkedin-in.jsx')['default']
  const IconFeMouse: typeof import('~icons/fe/mouse.jsx')['default']
  const IconIcOutlineEmail: typeof import('~icons/ic/outline-email.jsx')['default']
  const IconIonChevronDown: typeof import('~icons/ion/chevron-down.jsx')['default']
  const IconIonLogoGithub: typeof import('~icons/ion/logo-github.jsx')['default']
  const IconLucideExternalLink: typeof import('~icons/lucide/external-link.jsx')['default']
  const http: typeof import('axios')['default']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
