// Generated by 'unplugin-auto-import'
export {}
declare global {
  const http: typeof import('axios')['default']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
